---
title: Personal Website with Blogdown
author: Heidi Steiner
date: '2020-05-18'
slug: personal-website
categories:
  - R
tags:
  - Hugo
  - R Markdown
  - GitHub
  - blogdown
  - Academic
subtitle: ''
summary: ''
authors: []
lastmod: '2020-05-18T15:52:30-07:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
library(tidyverse)
library(knitr)
```
Creating a website has absolutely been a wild ride! I jumped between tutorials (and themes and hosts and generators) before finding the one I liked the best: [Summer of Blogdown](https://summer-of-blogdown.netlify.app/) by Alison Hill. 

The basic steps are as follows:

1. Create a new GitHub repository (or fork from a hugo theme you like)

2. Create new RStudio project via git clone (File > New Project > Version Control > Git)

3. Build the site...make sure to ```update_hugo()```, ```file.create("netlify.toml")```, and create a ```.gitignore``` file

4. Commit/Push to GitHub

5. Sign up for netlify (free)

6. Link GitHub website repository to netlify account

7. Configure ```config.toml``` file in the root of your project

8. Commit/Push

9. Enjoy almost instant site deploys! 


In the [Summer of Blogdown](https://summer-of-blogdown.netlify.app/) tutorial I learned to do all this and more. Personalizing this site isn't a breeze but it's not difficult either. 